import { PageContainer } from "../../components/Page";
import PageLeftBar from "../../components/navigation/PageLeftBar";
import PageBottomBar from "../../components/navigation/PageBottomBar";
import { NextPage } from "next";
import Head from "next/head";
import PageTopBar from "../../components/navigation/PageTopBar";
import PageRightBar from "../../components/navigation/PageRightBar";
import { useAuth } from "@clerk/nextjs";
import { trpc } from "../../utils/trpc";
import { OnboardingModal } from "../../components/onboarding/OnboardingModal";

const PAGE_COLOR = "#f2aa4b";

const Test: NextPage = () => {
  const { userId } = useAuth();

  const teacher = trpc.teacher.byId.useQuery(userId ?? "", {
    enabled: !!userId,
  });

  return (
    <>
      <Head>
        <title>Report Cards</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content={PAGE_COLOR}></meta>
      </Head>
      <PageContainer
        pageBottomBar={<PageBottomBar />}
        pageLeftBar={<PageLeftBar />}
        pageRightBar={<PageRightBar />}
        pageTopBar={<PageTopBar />}
        path="/test"
      >
        {!teacher.isLoading && teacher.data ? (
          <div className="flex w-full flex-col items-center">
            <div className="m-2 h-32 w-32 rounded-lg bg-yellow-400 shadow-lg">
              x
            </div>
            <div className="m-2 h-32 w-32 rounded-lg bg-yellow-400 shadow-lg">
              x
            </div>{" "}
            <div className="m-2 h-32 w-32 rounded-lg bg-yellow-400 shadow-lg">
              x
            </div>
          </div>
        ) : teacher.isLoading ? (
          <div>Loading</div>
        ) : (
          <OnboardingModal />
        )}
      </PageContainer>
    </>
  );
};

export default Test;
