import { PageContainer } from "../../../components/Page";
import PageLeftBar from "../../../components/navigation/PageLeftBar";
import PageBottomBar from "../../../components/navigation/PageBottomBar";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import PageTopBar from "../../../components/navigation/PageTopBar";
import PageRightBar from "../../../components/navigation/PageRightBar";
import { useRouter } from "next/router";
import { prisma } from "@acme/db";
import { buildClerkProps, getAuth } from "@clerk/nextjs/server";
import ClassForm from "../../../components/ClassForm";

const PAGE_COLOR = "#58c1fa";

const ClassPage: NextPage = () => {
  const router = useRouter();
  const { classId } = router.query;

  return (
    <>
      <Head>
        <title>Report Cards</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content={PAGE_COLOR}></meta>
      </Head>
      <PageContainer
        pageBottomBar={<PageBottomBar />}
        pageLeftBar={<PageLeftBar />}
        pageRightBar={<PageRightBar />}
        pageTopBar={<PageTopBar />}
        path="/class"
      >
        <div className="pb-8">{classId ?? "wtf"}</div>
        <ClassForm />
      </PageContainer>
    </>
  );
};

export default ClassPage;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const classId = context?.params?.classId;
  const { userId } = getAuth(context.req);

  if (typeof classId === "string" && typeof userId === "string") {
    const user = await prisma.class.findFirst({
      where: {
        id: classId,
        teacherId: userId,
      },
      select: { id: true },
    });

    if (user) {
      return { props: { ...buildClerkProps(context.req) } };
    }
  }

  return {
    redirect: {
      destination: "/404",
      permanent: false,
    },
  };
};
