import { PageContainer } from "../../components/Page";
import PageLeftBar from "../../components/navigation/PageLeftBar";
import PageBottomBar from "../../components/navigation/PageBottomBar";
import { NextPage } from "next";
import Head from "next/head";
import PageTopBar from "../../components/navigation/PageTopBar";
import PageRightBar from "../../components/navigation/PageRightBar";
import ClassTable from "../../components/ClassTable";

const PAGE_COLOR = "#58c1fa";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Report Cards</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content={PAGE_COLOR}></meta>
      </Head>
      <PageContainer
        pageBottomBar={<PageBottomBar />}
        pageLeftBar={<PageLeftBar />}
        pageRightBar={<PageRightBar />}
        pageTopBar={<PageTopBar />}
        path="/dashboard"
      >
        <div className="pb-8">
          <ClassTable />
        </div>
      </PageContainer>
    </>
  );
};

export default Dashboard;
