import { PageContainer } from "../../components/Page";
import PageLeftBar from "../../components/navigation/PageLeftBar";
import PageBottomBar from "../../components/navigation/PageBottomBar";
import { NextPage } from "next";
import Head from "next/head";
import PageTopBar from "../../components/navigation/PageTopBar";
import PageRightBar from "../../components/navigation/PageRightBar";
import ClassTable from "../../components/ClassTable";
import { trpc } from "../../utils/trpc";
import NoClasses from "../../components/NoClasses";
import DotLoader from "../../components/DotLoader/DotLoader";

const PAGE_COLOR = "#58c1fa";

const Dashboard: NextPage = () => {
  const { data, isLoading } = trpc.class.classes.useQuery();

  return (
    <>
      <Head>
        <title>Report Cards</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content={PAGE_COLOR}></meta>
      </Head>
      <PageContainer
        pageBottomBar={<PageBottomBar />}
        pageLeftBar={<PageLeftBar />}
        pageRightBar={<PageRightBar />}
        pageTopBar={<PageTopBar />}
        path="/dashboard"
      >
        <div className="pb-8">
          {isLoading ? (
            <div className="flex w-full justify-center pt-2">
              <DotLoader color="bg-sky-300/70" />
            </div>
          ) : !!data && data.length > 0 ? (
            <ClassTable classes={data} />
          ) : (
            <NoClasses />
          )}
        </div>
      </PageContainer>
    </>
  );
};

export default Dashboard;
